export const GOODS_CONFIG = [
  {
    id: 0,
    imgUrl: 'img/нагруднк.png',
    title: 'Нагрудник',
    subtitle: 'Мелкий опт от 5 шт.',
    price: 8500,
    sizes: [46, 48, 50, 54],
    activeSize: 48,
  },
  {
    id: 1,
    imgUrl: 'img/налакотники.png',
    title: 'Налокотники',
    subtitle: 'Мелкий опт от 5 шт.',
    price: 5900,
    sizes: [46, 48, 50, 54],
    activeSize: 50,
  },
  {
    id: 2,
    imgUrl: 'img/трусы.png',
    title: 'Трусы',
    subtitle: 'Мелкий опт от 5 шт.',
    price: 9650,
    sizes: [46, 48, 50, 54],
    activeSize: 54,
  },
  {
    id: 3,
    imgUrl: 'img/шлем.png',
    title: 'Шлем',
    subtitle: 'Мелкий опт от 5 шт.',
    price: 4620,
    sizes: [46, 48, 50, 54],
    activeSize: 48,
  },
  {
    id: 4,
    imgUrl: 'img/щитки.png',
    title: 'Щитки',
    subtitle: 'Мелкий опт от 5 шт.',
    price: 6900,
    sizes: [46, 48, 50, 54],
    activeSize: 50,
  },
  {
    id: 5,
    imgUrl: 'img/краги.png',
    title: 'Краги',
    subtitle: 'Мелкий опт от 5 шт.',
    price: 6290,
    sizes: [46, 48, 50, 54],
    activeSize: 54,
  },
]